### ISSUE TITLE
Self transition prevent next transition

### ISSUE THREAD

**Issue by jmatsushita** [davidkpiano/estado#4]
Hi there,

I might be misunderstanding something but adding a self transition seems to prevent other transitions with the same starting state to occur. For example this properly results in the `closed` state:

```
let review = machine(`
  init -> opened (OPEN)
  opened -> closed (CLOSE)
  closed!
`);

let newState = review.transition('opened', 'CLOSE');
// => 'closed' as expected
```

However the below returns false:

```
let review = machine(`
  init -> opened (OPEN)
  opened <- (UPDATE)
  opened -> closed (CLOSE)
  closed!
`);

let newState = review.transition('opened', 'CLOSE');
// => 'closed' as expected

// => false
```

Cheers,

Jun

**Comment by jmatsushita** [comment]
Actually it doesn't seem possible to have to transitions going out from the same state such as
```
a -> b (B)
a -> c (C)
```

Is that by design?

**Comment by davidkpiano** [comment]
Try this:

```
opened
  <- (UPDATE)
  -> closed (CLOSE)
```

**Comment by jmatsushita** [comment]
Thanks it works!
